const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("fengyueBackend", {
  getAppVersion: () => ipcRenderer.invoke("app:get-version"),
  getReleaseChannel: () => ipcRenderer.invoke("app:get-release-channel"),
  openOfficialReleasePage: () => ipcRenderer.invoke("app:open-official-release-page"),
  checkForUpdates: () => ipcRenderer.invoke("app:check-for-updates"),
  requestAppUpdate: () => ipcRenderer.invoke("app:request-update"),
  getAuthorInfo: () => ipcRenderer.invoke("app:get-author-info"),
  openAuthorLink: key => ipcRenderer.invoke("app:open-author-link", key),
  quitApp: () => ipcRenderer.invoke("app:quit"),
  getState: () => ipcRenderer.invoke("backend:get-state"),
  confirmAction: options => ipcRenderer.invoke("backend:confirm-action", options),
  getLogs: () => ipcRenderer.invoke("backend:get-logs"),
  listDomainCandidates: () => ipcRenderer.invoke("backend:list-domain-candidates"),
  listDomains: force => ipcRenderer.invoke("backend:list-domains", force),
  setOrigin: origin => ipcRenderer.invoke("backend:set-origin", origin),
  switchOrigin: origin => ipcRenderer.invoke("backend:switch-origin", origin),
  logout: () => ipcRenderer.invoke("backend:logout"),
  login: credentials => ipcRenderer.invoke("backend:login", credentials),
  autoLogin: credentials => ipcRenderer.invoke("backend:auto-login", credentials),
  cancelLogin: () => ipcRenderer.invoke("backend:cancel-login"),
  oauthLogin: provider => ipcRenderer.invoke("backend:oauth-login", provider),
  createRoom: settings => ipcRenderer.invoke("backend:create-room", settings),
  joinRoom: settings => ipcRenderer.invoke("backend:join-room", settings),
  removeRoomMember: memberId => ipcRenderer.invoke("backend:remove-room-member", memberId),
  leaveRoom: () => ipcRenderer.invoke("backend:leave-room"),
  sendRoomChat: value => ipcRenderer.invoke("backend:send-room-chat", value),
  submitRound: value => ipcRenderer.invoke("backend:submit-round", value),
  copyText: value => ipcRenderer.invoke("backend:copy-text", value),
  loadCredentials: () => ipcRenderer.invoke("credentials:load"),
  clearCredentials: () => ipcRenderer.invoke("credentials:clear"),
  setBounds: bounds => ipcRenderer.invoke("backend:set-bounds", bounds),
  setTheme: theme => ipcRenderer.invoke("backend:set-theme", theme),
  setSettingsVisible: visible => ipcRenderer.invoke("backend:set-settings-visible", visible),
  showLogin: () => ipcRenderer.invoke("backend:show-login"),
  chooseWork: () => ipcRenderer.invoke("backend:choose-work"),
  refreshConversations: () => ipcRenderer.invoke("backend:refresh-conversations"),
  selectConversation: conversationId => ipcRenderer.invoke("backend:select-conversation", conversationId),
  newConversation: () => ipcRenderer.invoke("backend:new-conversation"),
  renameConversation: (id, name) => ipcRenderer.invoke("backend:rename-conversation", id, name),
  deleteConversation: id => ipcRenderer.invoke("backend:delete-conversation", id),
  adaptWorkPrefix: () => ipcRenderer.invoke("backend:adapt-work-prefix"),
  updatePluginSettings: (pluginId, settings) => ipcRenderer.invoke("backend:update-plugin-settings", pluginId, settings),
  refreshWorkSettings: () => ipcRenderer.invoke("backend:refresh-work-settings"),
  updateWorkSettings: settings => ipcRenderer.invoke("backend:update-work-settings", settings),
  refreshModels: () => ipcRenderer.invoke("backend:refresh-models"),
  cancelModelRequests: () => ipcRenderer.invoke("backend:cancel-model-requests"),
  setModel: model => ipcRenderer.invoke("backend:set-model", model),
  runMessageOperation: (action, value) => ipcRenderer.invoke("backend:message-operation", action, value),
  injectPrototypeToolCard: () => ipcRenderer.invoke("backend:inject-prototype-tool-card"),
  createCharacterProfile: () => ipcRenderer.invoke("profiles:create"),
  saveCharacterProfile: profile => ipcRenderer.invoke("profiles:save", profile),
  selectCharacterProfile: profileId => ipcRenderer.invoke("profiles:select", profileId),
  deleteCharacterProfile: profileId => ipcRenderer.invoke("profiles:delete", profileId),
  showIntro: () => ipcRenderer.invoke("backend:show-intro"),
  showGame: () => ipcRenderer.invoke("backend:show-game"),
  scrollGame: deltaY => ipcRenderer.invoke("backend:scroll-game", deltaY),
  gamePointer: payload => ipcRenderer.invoke("backend:game-pointer", payload),
  gameKey: payload => ipcRenderer.invoke("backend:game-key", payload),
  hidePlatform: () => ipcRenderer.invoke("backend:hide-platform"),
  getOnlineWorldState: () => ipcRenderer.invoke("online-world:get-state"),
  listOnlineWorldCards: () => ipcRenderer.invoke("online-world:list-cards"),
  importOnlineWorldCard: () => ipcRenderer.invoke("online-world:import-card"),
  importOnlineWorldCardFiles: files => {
    const paths = Array.from(files || [], file => webUtils.getPathForFile(file)).filter(Boolean);
    return ipcRenderer.invoke("online-world:import-card-files", paths);
  },
  removeOnlineWorldCard: libraryId => ipcRenderer.invoke("online-world:remove-card", libraryId),
  exportOnlineWorldCard: cardId => ipcRenderer.invoke("online-world:export-card", cardId),
  openOnlineWorld: options => ipcRenderer.invoke("online-world:open", options),
  followOnlineWorldMigration: options => ipcRenderer.invoke("online-world:follow-migration", options),
  closeOnlineWorld: () => ipcRenderer.invoke("online-world:close"),
  initializeOnlineWorld: () => ipcRenderer.invoke("online-world:initialize"),
  syncOnlineWorld: full => ipcRenderer.invoke("online-world:sync", full),
  submitOnlineWorldIntent: intent => ipcRenderer.invoke("online-world:submit-intent", intent),
  sendOnlineWorldDirect: message => ipcRenderer.invoke("online-world:send-direct", message),
  migrateOnlineWorld: () => ipcRenderer.invoke("online-world:migrate"),
  administerOnlineWorld: command => ipcRenderer.invoke("online-world:administer", command),
  resetOnlineWorldData: () => ipcRenderer.invoke("online-world:reset-own-data"),
  updateOnlineWorldPreferences: preferences => ipcRenderer.invoke("online-world:update-preferences", preferences),
  newInstance: profileId => ipcRenderer.invoke("backend:new-instance", profileId),
  onState: callback => ipcRenderer.on("backend:state", (_event, state) => callback(state)),
  onGameFrame: callback => ipcRenderer.on("backend:game-frame", (_event, frame) => callback(frame)),
  onOnlineWorldState: callback => ipcRenderer.on("online-world:state", (_event, state) => callback(state)),
  onLog: callback => ipcRenderer.on("backend:log", (_event, entry) => callback(entry))
});
